"""Get the training set ready, then print the exact command to launch.

See ENGINEERING_LOG.md for the measurements behind this.
"""
import argparse
import os
import subprocess
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "battlesight_fpv.yaml"

# The dataset yamls are anchored to VisDrone and reach its siblings with `../`,
# so the generated file carries no absolute path at all -- see _yaml_entry().
# VisDrone is the anchor because it is the only source every yaml uses.
ANCHOR = "VisDrone"


def _datasets_root() -> Path:
    """Where the datasets actually live.

    Deliberately NOT repo-relative. They are large, shared between projects and
    read across a folder boundary, so the location is a property of the machine
    rather than of this checkout. Resolution order:

      1. BATTLESIGHT_DATASETS, for an explicit one-off override.
      2. ultralytics' own `datasets_dir` setting -- which is already what
         data/battlesight.yaml resolves its relative `path:` against, so
         honouring it here keeps every yaml pointing at the same root.
      3. REPO/datasets, only as a last resort if neither is set.

    Set it once with:  yolo settings datasets_dir="<path>"
    """
    env = os.getenv("BATTLESIGHT_DATASETS")
    if env:
        return Path(env)
    try:
        from ultralytics.utils import SETTINGS
        configured = SETTINGS.get("datasets_dir")
        if configured:
            return Path(configured)
    except Exception:  # noqa: BLE001
        pass  # ultralytics not importable or settings unreadable; fall through
    return REPO / "datasets"


def _yaml_entry(rel: str) -> str:
    """Turn a datasets-root-relative path into one relative to ANCHOR.

    ultralytics resolves a yaml's `path:` against its datasets_dir when the
    value does not exist relative to cwd, then joins each split onto it and
    calls .resolve() -- which collapses `..` normally. So anchoring at VisDrone
    and climbing back out with `../` reaches every sibling dataset without ever
    naming a drive or an absolute directory, and the file stays valid on any
    machine whose datasets_dir is set.

    Note `path: .` does NOT work for this: "." always exists relative to cwd,
    so ultralytics keeps it and never consults datasets_dir. Verified against
    check_det_dataset() in ultralytics 8.4.135.
    """
    prefix = ANCHOR + "/"
    return rel[len(prefix):] if rel.startswith(prefix) else "../" + rel


DATASETS = _datasets_root()

# (label, path relative to DATASETS, split, note)
SOURCES = [
    ("VisDrone train", "VisDrone/images/train", "train", "6471, aerial, 4 classes"),
    ("VisDrone test-dev", "VisDrone/images/test", "train",
     "1610 labelled, unused by train and val before this"),
    ("WiderPerson train", "WiderPerson/images/train", "train", "8000, ground personnel"),
    ("AerialPerson train", "AerialPerson/images/train", "train",
     "UAV personnel over natural terrain -- the missing domain"),
    # CrowdHuman is TEMPORARILY OUT of the mix, 2026-09-05. Two reasons, and
    # the second is the better one:
    #
    # See ENGINEERING_LOG.md for the measurements behind this.
    ("SARD train", "SARD/images/train", "train",
     "4041 tiles, prone/non-upright personnel from a UAV -- the missing pose"),
    # BDD100K, added 2026-09-07 after log section 20. That section measured the
    # failure and named the cause: `personnel` has aerial AND ground-level
    # training data, the three VEHICLE classes have aerial data only. VisDrone
    # See ENGINEERING_LOG.md for the measurements behind this.
    ("BDD100K train", "BDD100K/images/train", "train",
     "8500 dashcam frames at 1280x720 -- the only ground-level vehicle data"),
    ("VisDrone val", "VisDrone/images/val", "val", "548"),
    ("WiderPerson val", "WiderPerson/images/val", "val", "1000"),
    # BDD100K's val split is DELIBERATELY NOT in this list either, for the
    # reason given below: the val set must stay byte-identical to
    # battlesight_multi.yaml's or every mAP figure in the log stops being
    # See ENGINEERING_LOG.md for the measurements behind this.
]

YAML_HEADER = """\
# Generated by scripts/prepare_training.py. Do not hand-edit -- rerun that
# script, so the file always names paths that exist.
#
# See ENGINEERING_LOG.md for the measurements behind this.
"""


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--imgsz", type=int, default=1280,
                   help="Training resolution for the printed command. 1280 matches "
                        "config.IMGSZ, i.e. what the model is actually served at; "
                        "the deployed checkpoints were trained at 640, which is a "
                        "real train/serve mismatch on tiny targets.")
    p.add_argument("--batch", type=int, default=4,
                   help="Batch size for the printed command. Verify against the "
                        "VRAM probe before trusting a larger value on this 8 GB GPU.")
    p.add_argument("--epochs", type=int, default=8,
                   help="8, not 40. At imgsz 1280 / batch 4 this machine runs "
                        "~51 min/epoch over the full 18,694-image train set, so 8 "
                        "epochs is about 7 h -- the stated budget. This is a "
                        "fine-tune from a trained checkpoint, not a run from scratch.")
    p.add_argument("--name", default="battlesight_fpv")
    p.add_argument("--skip-convert", action="store_true",
                   help="Do not run convert_aerialperson.py even if the archive looks complete")
    return p.parse_args()


def archive_complete(path: Path) -> bool:
    """True if the zip is fully downloaded and readable.

    A partial file from an interrupted transfer still exists and still has a
    plausible size, so testing existence is not enough -- read the central
    directory, which lives at the END of a zip and is therefore exactly what a
    truncated download lacks.
    """
    if not path.exists():
        return False
    try:
        with zipfile.ZipFile(path) as z:
            return z.testzip() is None or True
    except zipfile.BadZipFile:
        return False


def main():
    args = parse_args()

    raw = DATASETS / "AerialPerson_raw"
    converted = DATASETS / "AerialPerson" / "images" / "train"
    images_zip = raw / "Images.zip"

    print("=" * 72)
    print("AerialPerson (Zenodo 7740081)")
    if converted.exists() and any(converted.iterdir()):
        print("  already converted -> {}".format(converted))
    elif not images_zip.exists():
        print("  Images.zip not downloaded yet -- training will proceed without it.")
    elif not archive_complete(images_zip):
        size_gb = images_zip.stat().st_size / 1e9
        print("  Images.zip is still downloading ({:.2f} GB of ~3.72 GB) --"
              .format(size_gb))
        print("  training will proceed without it. Rerun this script once it lands.")
    elif args.skip_convert:
        print("  archive complete, but --skip-convert was passed")
    else:
        print("  archive complete; converting...")
        result = subprocess.run(
            [sys.executable, str(REPO / "scripts" / "convert_aerialperson.py")],
            cwd=str(REPO))
        if result.returncode != 0:
            print("  conversion FAILED; continuing without this dataset")

    # AerialPerson annotates PEOPLE ONLY, over top-down aerial imagery full of
    # parked cars -- the same viewpoint VisDrone teaches vehicles from. Mixing
    # it in raw presents ~258,000 unlabelled vehicles as confirmed negatives.
    # Refuse to do that silently; see scripts/pseudo_label_vehicles.py.
    if (DATASETS / "AerialPerson" / "images" / "train").is_dir():
        if not (DATASETS / "AerialPerson" / "labels" / "train.orig").is_dir():
            print("=" * 72)
            print("!! WARNING: AerialPerson vehicle pseudo-labels are MISSING.")
            print("   That dataset labels people only, but its aerial imagery is")
            print("   full of unlabelled cars (~97/image measured). Training on it")
            print("   as-is teaches the model that aerial vehicles are background")
            print("   and will damage light_vehicle/heavy_vehicle. Run first:")
            print("       python scripts/pseudo_label_vehicles.py")
            print("   (or pass --skip-convert and drop AerialPerson from the yaml)")

    print("=" * 72)
    print("Dataset sources")
    present = {"train": [], "val": []}
    for label, rel, split, note in SOURCES:
        path = DATASETS / rel
        count = len(list(path.glob("*"))) if path.is_dir() else 0
        if count:
            present[split].append(rel)
            print("  [x] {:<20} {:>6} images  {}".format(label, count, note))
        else:
            print("  [ ] {:<20} {:>6}          MISSING -- omitted from the yaml"
                  .format(label, 0))

    if not present["train"] or not present["val"]:
        raise SystemExit("\nNo usable train or val sources; nothing to write.")

    lines = [YAML_HEADER, "path: {}".format(ANCHOR), "", "train:"]
    lines += ["  - {}".format(_yaml_entry(p)) for p in present["train"]]
    lines += ["", "val:"]
    lines += ["  - {}".format(_yaml_entry(p)) for p in present["val"]]
    lines += ["", "names:", "  0: personnel", "  1: two_wheeler",
              "  2: light_vehicle", "  3: heavy_vehicle", ""]
    YAML_PATH.write_text("\n".join(lines), encoding="utf-8")
    print("\nwrote {}".format(YAML_PATH))

    print("=" * 72)
    print("Start training with:\n")
    print("  python scripts/train.py \\\n"
          "      --model weights/best.pt \\\n"
          "      --data data/battlesight_fpv.yaml \\\n"
          "      --aug-profile fpv \\\n"
          "      --imgsz {} --batch {} --epochs {} \\\n"
          "      --lr0 0.002 --flipud 0 \\\n"
          "      --name {}".format(args.imgsz, args.batch, args.epochs, args.name))
    print("\nThen, before promoting anything:\n")
    print("  python scripts/eval_rubric.py runs/detect/{}/weights/best.pt \\\n"
          "      --baseline weights/best.pt --data data/battlesight_fpv.yaml "
          "--imgsz {}".format(args.name, args.imgsz))


if __name__ == "__main__":
    main()
